#include <stack>
#include <string>
#include <cstring>
#include <sstream>
#include <omp.h>
#include <math.h>
#include <stdlib.h>
#include <unordered_map>
#include <ctime>
#include <fstream>
#include <algorithm>
#include <map>
#include <vector>
#include <iostream>
#include <ostream>
#include <unordered_set>
#include <set>
#include <memory>

/*
 * Written by Jim Shaw - jimshawster@gmail.com during his undergraduate research
 * assistantship at the University of Waterloo. August 2nd, 2018
 */

//Change to specify number of threads.
const int NUM_THREADS = 8;

//Global prime variable. Initialization value doesn't matter.
unsigned char  p =7; 

std::vector<std::vector<std::pair<std::vector<int>,std::vector<int>>>> sub_maps;
std::map<int,int> size_map;

//Dummy vectors - serve as a memory location to point to.
std::vector<int>svect =  std::vector<int>({0});
std::vector<int>pvect = std::vector<int>({-2}); 

inline bool isInteger(const std::string & s)
{
   if(s.empty() || ((!isdigit(s[0])) && (s[0] != '-') && (s[0] != '+'))) return false ;

   char * k ;
   strtol(s.c_str(), &k, 10) ;

   return (*k == 0) ;
}

//Monomial - [0,0,1,1] represents x_3x_4,
//[1,0,2,0] represents x_1x_3^2, etc
struct monomial{
    std::vector<unsigned char> vars;

    bool operator==(const monomial &other) const{
        return (vars == other.vars);
    }

    monomial(){};
};

//{<[1,0,2,0],-1>,<[0,1,1,1],5>} represents  5*x_2x_3x_4 - x_1x_3^2
typedef std::unordered_map<monomial,int> polynomial;

//Represents index-exponent pairs for monomials, [[1,5],[3,2]] = [0,5,0,2]
//I think taking out the zeroes made this representation slightly faster
//when we don't need the key,pair structure.
struct vect_mono{

    bool operator==(const vect_mono &other) const{
        return (vars == other.vars);
    }

    std::vector<std::pair<unsigned char,unsigned char>> vars;

    vect_mono(const monomial& mon)
    {
        vars.reserve(mon.vars.size() + 1);
        for(int i = 0,end = mon.vars.size(); i < end; i++){
            if(mon.vars[i] != 0){
                vars.emplace_back(i,mon.vars[i]);
            }
        }
    }
    
    vect_mono(){};

};

//Convenient representation of a polynomial of the form (a_1a_2..)^exponent * (a_i...)^exp)
struct monomial_x{
    std::vector<int>* xvars;
    std::vector<int>* vars;
    long int cf;
    unsigned char exponent;
    unsigned char exp;

    monomial_x( std::vector<int>* xvars,  std::vector<int>* vars, unsigned char expx,
            unsigned char exp, int a_cf, unsigned char x_exp): xvars(xvars), vars(vars), cf(a_cf), exponent(x_exp),
   exp(exp) {

       if(!xvars->empty()){
           if((*xvars)[0] < 0){
               if ((*xvars)[0] != -2){
                   if(exponent %2 == 1){
                       cf *= -1;
                   }
               }
           }
       }

       if(!vars->empty()){
            if((*vars)[0] < 0){
               if ((*vars)[0] != -2){
                   if(exp %2 == 1){
                       cf *= -1;
                   }
               }
           }
       }
   }
};

//A node in the DAG generated by determining which monomials to multiply which
//will give a term with x^{p-1}
struct mono_x_node{
    monomial_x* mon_ptr;
    std::vector<mono_x_node*> children;
    mono_x_node(monomial_x* monx) : mon_ptr(monx){
        children.reserve(p);
    }

    ~mono_x_node(){
        for(unsigned int i = 0; i < children.size(); i++){
            delete children[i];
        }
    }

    mono_x_node(){
    }
};

//Process a recipe file, obtain substitutions and factors to run algorithm.
//The idea is to get your old variables for each iteration, u_1...u_n and 
//be able to substitute u_1 |-> y_1y_2...x + y_ny_(n+1)...
//There is some complicated data processing to be done since we have to 
//represent each u_i, y_i as an index of an array.
void process_recipe(std::vector<std::vector<std::pair<std::vector<int>,std::vector<int>>>>& sub_maps,
        std::map<int,int>& size_map, std::string recipe_name){

    //Dodgson file is a pretty bad name for the file -- jim
    std::ifstream dodgson_file(recipe_name);
    int num_iter = 0;

    if(dodgson_file.is_open())
    {
        std::set<std::string> var_set_new;
        std::set<std::string> var_set_old;
        std::map<std::string,int> old_to_index;
        std::map<std::string,int> new_to_index;
        std::vector<std::pair<std::vector<int>,std::vector<int>>> sub_map;
        std::string line;
        bool first = true;
        while(std::getline(dodgson_file,line)){

            int numvar = 0;
            if(line[0] == '>'){

               numvar = std::stoi(line.substr(1));
               size_map.insert(std::make_pair(num_iter,numvar));
                if(!first){
                   sub_maps.push_back(sub_map);
                }
               sub_map.clear();
               sub_map.resize(size_map[num_iter]);
               var_set_new.clear();
               var_set_old.clear();
               old_to_index.clear();
               new_to_index.clear();
               num_iter++;
               first = true;
            }

            else if(line[0] == '-'){
                var_set_old.insert(line.substr(1));
            }

            else if(line[0] == '+'){
                var_set_new.insert(line.substr(1));
            }

            else if(line[0] != '>'){
                if(first){
                    int itcount = 0;
                    for(auto it = var_set_old.begin(),end = var_set_old.end(); it != end; ++it){
                        old_to_index.insert(std::make_pair(*it,itcount)); 
                        std::cout << itcount << " " << *it << ' ';
                        itcount++;
                    }
                    std::cout << var_set_old.size() << "\n";

                    itcount = 0;
                    for(auto it = var_set_new.begin(),end = var_set_new.end(); it != end; ++it){
                        new_to_index.insert(std::make_pair(*it,itcount)); 
                        std::cout << itcount << " " << *it << ' ';
                        itcount++;
                    }
                    std::cout<< var_set_new.size()  << "\n";
                    first = false;
                }

                int pos1 = line.find(',');
                std::string var = line.substr(0,pos1);
                line.erase(0,pos1+1);

                std::vector<int> x_vars;
                std::vector<int> nox_vars;

                int pos2 = line.find(',');
                std::string xvars_line = line.substr(0,pos2);
                line.erase(0,pos2+1);

                size_t inter_pos;

                if(isInteger(xvars_line)){
                    int x = std::stoi(xvars_line);
                    //We use dummy numbers to represent specific factorizations
                    //-2 implies that the monomial is just 1,
                    //-3 implies the monomial is just -1
                    if(x == 1){
                        x_vars.push_back(-2);
                    }
                    if(x == -1){
                        x_vars.push_back(-3);
                    }
                }
                    
                else{
//                    std::cout << var << ' ' << xvars_line << " line " << '\n';
//                    If negative we push a specific number -1 to indicate that our monomial is negative.
//                    Usually this number is an index representing the variable u_i or y_i.
                    if(xvars_line[0] == '-'){
                        x_vars.push_back(-1);
                        xvars_line = xvars_line.substr(1);
                    }

                    while((inter_pos = xvars_line.find('*')) != std::string::npos){
                        std::string token = xvars_line.substr(0,inter_pos);
                        x_vars.push_back(new_to_index[token]);
                        xvars_line.erase(0,inter_pos+1);
                    }
                    x_vars.push_back(new_to_index[xvars_line]);
                }

                if(isInteger(line)){
                    int x = std::stoi(line);
                    if(x == 1){
                        nox_vars.push_back(-2);
                    }
                    if(x == -1){
                        nox_vars.push_back(-3);
                    }
                }

                else{
//                std::cout << var << ' ' <<  line << " line " << '\n';
                    if(line[0] == '-'){
                        nox_vars.push_back(-1);
                        line = line.substr(1);
                    }

                    while((inter_pos = line.find('*')) != std::string::npos){
                        std::string token = line.substr(0,inter_pos);
                        nox_vars.push_back(new_to_index[token]);
                        line.erase(0,inter_pos+1);
                    }

                    nox_vars.push_back(new_to_index[line]);
                }

//                std::cout << sub_map.size()  << old_to_index[var] << '\n';
                sub_map[old_to_index[var]] = std::make_pair(x_vars,nox_vars);
            }

        }
        dodgson_file.close();
    }

	else{
		std::cout << "file couldn't be opened";
		exit(1);
	}
    
}

//openmp specifies that we must iterate over a random access iterator container, so we
//represent the polynomial in a vector just for the iteration procedure.
typedef std::vector<std::pair<vect_mono,int>> iter_polyn; 

//Custom hash function for an array (i.e. our monomial).
namespace std{

    template <>
    struct hash<monomial> {

        //Taken shamelessly from stackoverflow somewhere.
        std::size_t operator()(const monomial& k) const
        {
            std::size_t toreturn = 17;

            using std::hash;

            for(int i = 0, end = k.vars.size(); i <end ; i++){
                if(k.vars[i] != 0){
                    toreturn ^= k.vars[i] + 311*i + 0x9e3779b9 + (toreturn << 6) + (toreturn >> 2);
                }
            }

            return toreturn;
        }
    };
}


//For debugging
std::ostream& operator<<(std::ostream& os, const monomial_x& m){
        os << m.cf << "*";

        for (unsigned int i = 0; i < m.xvars->size(); i++){
            os << (int)(*m.xvars)[i]<< "^" << (int)m.exponent <<  ' ';
        }

        for (unsigned int i = 0; i < m.vars->size(); i++){
            os << (int)(*m.vars)[i] << "^" << (int)m.exp <<  ' ';
        }

        return os;
}

//For debugging
std::ostream& operator<<(std::ostream& os, const vect_mono& m){

        for (unsigned int i = 0; i < m.vars.size(); i++){
            os << (int)m.vars[i].first << "^" <<  (int)m.vars[i].second << '*';
        }

        return os;
}

bool sort_function ( const std::vector<monomial_x>& vec1, const std::vector<monomial_x>& vec2){
    return (vec1.size() < vec2.size());
}

//This is where we do (u_i)^k |-> (y_1y_2...x + y_n...)^k. We can actually just do a lookup
//of (ax+b)^k so we don't actually have the calculate the entire thing.
std::vector<monomial_x>
tabled_lookup (unsigned char var, unsigned char exponent, unsigned int iteration){ 
    std::vector<int>* xvars = &sub_maps[iteration][var].first;
    std::vector<int>* vars = &sub_maps[iteration][var].second;    

    if(iteration+1 == size_map.size()){
        xvars = &svect;
        vars = &pvect;  
    }

    std::vector<int> emptyvect;
    
    bool b_zero = false;
    bool a_zero = false;

    if(xvars->empty()){
        a_zero = true;
    }
    
    if(vars->empty()){
        b_zero = true;
    }

    if(a_zero){
        return std::vector<monomial_x>({monomial_x(&emptyvect,vars,0,exponent,1,0)});
    }

    if(b_zero){
       return std::vector<monomial_x>({monomial_x(xvars,&emptyvect,exponent,0,1,exponent)});
    }

    if(a_zero && b_zero){
        std::cout << "both zero" << '\n';
        exit(0);
    }

    int NONE = 0;

    //Generated by maple.
    switch(exponent){
        case 1: {
                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,1,1,0),
                   monomial_x(xvars,&emptyvect,1,NONE,1,1)
                           });
                }

        case 2: {

                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,2,1,0),
                   monomial_x(xvars,vars,1,1,2%p,1),
                   monomial_x(xvars,&emptyvect,2,NONE,1,2)
                           });
                }

        case 3: {

                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,3,1,0),
                   monomial_x(xvars,vars,1,2,3%p,1),
                   monomial_x(xvars,vars,2,1,3%p,2),
                   monomial_x(xvars,&emptyvect,3,NONE,1,3)
                   });
                }
        case 4: {
                   
                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,4,1,0),
                   monomial_x(xvars,vars,1,3,4%p,1),
                   monomial_x(xvars,vars,2,2,6%p,2),
                   monomial_x(xvars,vars,3,1,4%p,3),
                   monomial_x(xvars,&emptyvect,4,NONE,1,4)
                   });
                }

        case 5: {
                   
                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,5,1,0),
                   monomial_x(xvars,vars,1,4,5%p,1),
                   monomial_x(xvars,vars,2,3,10%p,2),
                   monomial_x(xvars,vars,3,2,10%p,3),
                   monomial_x(xvars,vars,4,1,5%p,4),
                   monomial_x(xvars,&emptyvect,5,NONE,1,5)
                   });
                }
       case 6: {
                   
                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,6,1,0),
                   monomial_x(xvars,vars,1,5,6%p,1),
                   monomial_x(xvars,vars,2,4,15%p,2),
                   monomial_x(xvars,vars,3,3,20%p,3),
                   monomial_x(xvars,vars,4,2,15%p,4),
                   monomial_x(xvars,vars,5,1,6%p,5),
                   monomial_x(xvars,&emptyvect,6,NONE,1,6)
                   });
                }

      case 7: {
                   return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,7,1,0),
                   monomial_x(xvars,vars,1,6,7%p,1),
                   monomial_x(xvars,vars,2,5,21%p,2),
                   monomial_x(xvars,vars,3,4,35%p,3),
                   monomial_x(xvars,vars,4,3,35%p,4),
                   monomial_x(xvars,vars,5,2,21%p,5),
                   monomial_x(xvars,vars,6,1,7%p,6),
                   monomial_x(xvars,&emptyvect,7,NONE,1,7)
                   });

              }

      case 8: {
                   return std::vector<monomial_x>({
                    monomial_x(&emptyvect,vars,NONE,8,1,0),
                   monomial_x(xvars,vars,1,7,8%p,1),
                   monomial_x(xvars,vars,2,6,28%p,2),
                   monomial_x(xvars,vars,3,5,56%p,3),
                   monomial_x(xvars,vars,4,4,70%p,4),
                   monomial_x(xvars,vars,5,3,56%p,5),
                   monomial_x(xvars,vars,6,2,28%p,6),
                   monomial_x(xvars,vars,7,1,8%p,7),
                   monomial_x(xvars,&emptyvect,8,NONE,1,8)
                  });
              }

      case 9: {
                  return std::vector<monomial_x>({
                   monomial_x(&emptyvect,vars,NONE,9,1,0),
                   monomial_x(xvars,vars,1,8,9%p,1),
                   monomial_x(xvars,vars,2,7,36%p,2),
                   monomial_x(xvars,vars,3,6,84%p,3),
                   monomial_x(xvars,vars,4,5,126%p,4),
                   monomial_x(xvars,vars,5,4,126%p,5),
                   monomial_x(xvars,vars,6,3,84%p,6),
                   monomial_x(xvars,vars,7,2,36%p,7),
                   monomial_x(xvars,vars,8,1,9%p,8),
                   monomial_x(xvars,&emptyvect,9,NONE,1,9)
                  });

              }
      case 10:{
                    return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,10,1,0),
                   monomial_x(xvars,vars,1,9,10%p,1),
                   monomial_x(xvars,vars,2,8,45%p,2),
                   monomial_x(xvars,vars,3,7,120%p,3),
                   monomial_x(xvars,vars,4,6,210%p,4),
                   monomial_x(xvars,vars,5,5,252%p,5),
                   monomial_x(xvars,vars,6,4,210%p,6),
                   monomial_x(xvars,vars,7,3,120%p,7),
                   monomial_x(xvars,vars,8,2,45%p,8),
                   monomial_x(xvars,vars,9,1,10%p,9),
                   monomial_x(xvars,&emptyvect,10,NONE,1,10)
                  });

              }

      case 11:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,11,1,0),
                   monomial_x(xvars,vars,1,10,11%p,1),
                   monomial_x(xvars,vars,2,9,55%p,2),
                   monomial_x(xvars,vars,3,8,165%p,3),
                   monomial_x(xvars,vars,4,7,330%p,4),
                   monomial_x(xvars,vars,5,6,462%p,5),
                   monomial_x(xvars,vars,6,5,462%p,6),
                   monomial_x(xvars,vars,7,4,330%p,7),
                   monomial_x(xvars,vars,8,3,165%p,8),
                   monomial_x(xvars,vars,9,2,55%p,9),
                   monomial_x(xvars,vars,10,1,11%p,10),
                   monomial_x(xvars,&emptyvect,11,NONE,1,11)
                  });
              }
        case 12:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,12,1,0),
                   monomial_x(xvars,vars,1,11,12%p,1),
                   monomial_x(xvars,vars,2,10,66%p,2),
                   monomial_x(xvars,vars,3,9,220%p,3),
                   monomial_x(xvars,vars,4,8,495%p,4),
                   monomial_x(xvars,vars,5,7,792%p,5),
                   monomial_x(xvars,vars,6,6,924%p,6),
                   monomial_x(xvars,vars,7,5,792%p,7),
                   monomial_x(xvars,vars,8,4,495%p,8),
                   monomial_x(xvars,vars,9,3,220%p,9),
                   monomial_x(xvars,vars,10,2,66%p,10),
                   monomial_x(xvars,vars,11,1,12%p,11),
                   monomial_x(xvars,&emptyvect,12,NONE,1,12)
                  });
              }

        case 13:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,13,1,0),
                   monomial_x(xvars,vars,1,12,13%p,1),
                   monomial_x(xvars,vars,2,11,78%p,2),
                   monomial_x(xvars,vars,3,10,286%p,3),
                   monomial_x(xvars,vars,4,9,715%p,4),
                   monomial_x(xvars,vars,5,8,1287%p,5),
                   monomial_x(xvars,vars,6,7,1716%p,6),
                   monomial_x(xvars,vars,7,6,1716%p,7),
                   monomial_x(xvars,vars,8,5,1287%p,8),
                   monomial_x(xvars,vars,9,4,715%p,9),
                   monomial_x(xvars,vars,10,3,286%p,10),
                   monomial_x(xvars,vars,11,2,78%p,11),
                   monomial_x(xvars,vars,12,1,13%p,12),
                   monomial_x(xvars,&emptyvect,13,NONE,1,13)
                  });
              }

        case 14:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,14,1,0),
                   monomial_x(xvars,vars,1,13,14%p,1),
                   monomial_x(xvars,vars,2,12,91%p,2),
                   monomial_x(xvars,vars,3,11,364%p,3),
                   monomial_x(xvars,vars,4,10,1001%p,4),
                   monomial_x(xvars,vars,5,9,2002%p,5),
                   monomial_x(xvars,vars,6,8,3003%p,6),
                   monomial_x(xvars,vars,7,7,3432%p,7),
                   monomial_x(xvars,vars,8,6,3003%p,8),
                   monomial_x(xvars,vars,9,5,2002%p,9),
                   monomial_x(xvars,vars,10,4,1001%p,10),
                   monomial_x(xvars,vars,11,3,364%p,11),
                   monomial_x(xvars,vars,12,2,91%p,12),
                   monomial_x(xvars,vars,13,1,14%p,13),
                   monomial_x(xvars,&emptyvect,14,NONE,1,14)
                  });
              }

        case 15:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,15,1,0),
                   monomial_x(xvars,vars,1,14,15%p,1),
                   monomial_x(xvars,vars,2,13,105%p,2),
                   monomial_x(xvars,vars,3,12,455%p,3),
                   monomial_x(xvars,vars,4,11,1365%p,4),
                   monomial_x(xvars,vars,5,10,3003%p,5),
                   monomial_x(xvars,vars,6,9,5005%p,6),
                   monomial_x(xvars,vars,7,8,6435%p,7),
                   monomial_x(xvars,vars,8,7,6435%p,8),
                   monomial_x(xvars,vars,9,6,5005%p,9),
                   monomial_x(xvars,vars,10,5,3003%p,10),
                   monomial_x(xvars,vars,11,4,1365%p,11),
                   monomial_x(xvars,vars,12,3,455%p,12),
                   monomial_x(xvars,vars,13,2,105%p,13),
                   monomial_x(xvars,vars,14,1,15%p,14),
                   monomial_x(xvars,&emptyvect,15,NONE,1,15)
                  });
              }

        case 16:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,16,1,0),
                   monomial_x(xvars,vars,1,15,16%p,1),
                   monomial_x(xvars,vars,2,14,120%p,2),
                   monomial_x(xvars,vars,3,13,560%p,3),
                   monomial_x(xvars,vars,4,12,1820%p,4),
                   monomial_x(xvars,vars,5,11,4368%p,5),
                   monomial_x(xvars,vars,6,10,8008%p,6),
                   monomial_x(xvars,vars,7,9,11440%p,7),
                   monomial_x(xvars,vars,8,8,12870%p,8),
                   monomial_x(xvars,vars,9,7,11440%p,9),
                   monomial_x(xvars,vars,10,6,8008%p,10),
                   monomial_x(xvars,vars,11,5,4368%p,11),
                   monomial_x(xvars,vars,12,4,1820%p,12),
                   monomial_x(xvars,vars,13,3,560%p,13),
                   monomial_x(xvars,vars,14,2,120%p,14),
                   monomial_x(xvars,vars,15,1,16%p,15),
                   monomial_x(xvars,&emptyvect,16,NONE,1,16)
                  });
              }

        case 17:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,17,1,0),
                   monomial_x(xvars,vars,1,16,17%p,1),
                   monomial_x(xvars,vars,2,15,136%p,2),
                   monomial_x(xvars,vars,3,14,680%p,3),
                   monomial_x(xvars,vars,4,13,2380%p,4),
                   monomial_x(xvars,vars,5,12,6188%p,5),
                   monomial_x(xvars,vars,6,11,12376%p,6),
                   monomial_x(xvars,vars,7,10,19448%p,7),
                   monomial_x(xvars,vars,8,9,24310%p,8),
                   monomial_x(xvars,vars,9,8,24310%p,9),
                   monomial_x(xvars,vars,10,7,19448%p,10),
                   monomial_x(xvars,vars,11,6,12376%p,11),
                   monomial_x(xvars,vars,12,5,6188%p,12),
                   monomial_x(xvars,vars,13,4,2380%p,13),
                   monomial_x(xvars,vars,14,3,680%p,14),
                   monomial_x(xvars,vars,15,2,136%p,15),
                   monomial_x(xvars,vars,16,1,17%p,16),
                   monomial_x(xvars,&emptyvect,17,NONE,1,17)
                  });
              }

        case 18:{
                      return std::vector<monomial_x>({
                     monomial_x(&emptyvect,vars,NONE,18,1,0),
                   monomial_x(xvars,vars,1,17,18%p,1),
                   monomial_x(xvars,vars,2,16,153%p,2),
                   monomial_x(xvars,vars,3,15,816%p,3),
                   monomial_x(xvars,vars,4,14,3060%p,4),
                   monomial_x(xvars,vars,5,13,8568%p,5),
                   monomial_x(xvars,vars,6,12,18564%p,6),
                   monomial_x(xvars,vars,7,11,31824%p,7),
                   monomial_x(xvars,vars,8,10,43758%p,8),
                   monomial_x(xvars,vars,9,9,48620%p,9),
                   monomial_x(xvars,vars,10,8,43758%p,10),
                   monomial_x(xvars,vars,11,7,31824%p,11),
                   monomial_x(xvars,vars,12,6,18564%p,12),
                   monomial_x(xvars,vars,13,5,8568%p,13),
                   monomial_x(xvars,vars,14,4,3060%p,14),
                   monomial_x(xvars,vars,15,3,816%p,15),
                   monomial_x(xvars,vars,16,2,153%p,16),
                   monomial_x(xvars,vars,17,1,18%p,17),
                   monomial_x(xvars,&emptyvect,18,NONE,1,18)
                  });
              }

        case 19:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,19,1,0),
    monomial_x(xvars,vars,1,18,19%p,1),
    monomial_x(xvars,vars,2,17,171%p,2),
    monomial_x(xvars,vars,3,16,969%p,3),
    monomial_x(xvars,vars,4,15,3876%p,4),
    monomial_x(xvars,vars,5,14,11628%p,5),
    monomial_x(xvars,vars,6,13,27132%p,6),
    monomial_x(xvars,vars,7,12,50388%p,7),
    monomial_x(xvars,vars,8,11,75582%p,8),
    monomial_x(xvars,vars,9,10,92378%p,9),
    monomial_x(xvars,vars,10,9,92378%p,10),
    monomial_x(xvars,vars,11,8,75582%p,11),
    monomial_x(xvars,vars,12,7,50388%p,12),
    monomial_x(xvars,vars,13,6,27132%p,13),
    monomial_x(xvars,vars,14,5,11628%p,14),
    monomial_x(xvars,vars,15,4,3876%p,15),
    monomial_x(xvars,vars,16,3,969%p,16),
    monomial_x(xvars,vars,17,2,171%p,17),
    monomial_x(xvars,vars,18,1,19%p,18),
    monomial_x(xvars,&emptyvect,19,NONE,1,19)

                            });
                }

         case 20:{
                    return std::vector<monomial_x>({ 
    monomial_x(&emptyvect,vars,NONE,20,1,0),
    monomial_x(xvars,vars,1,19,20%p,1),
    monomial_x(xvars,vars,2,18,190%p,2),
    monomial_x(xvars,vars,3,17,1140%p,3),
    monomial_x(xvars,vars,4,16,4845%p,4),
    monomial_x(xvars,vars,5,15,15504%p,5),
    monomial_x(xvars,vars,6,14,38760%p,6),
    monomial_x(xvars,vars,7,13,77520%p,7),
    monomial_x(xvars,vars,8,12,125970%p,8),
    monomial_x(xvars,vars,9,11,167960%p,9),
    monomial_x(xvars,vars,10,10,184756%p,10),
    monomial_x(xvars,vars,11,9,167960%p,11),
    monomial_x(xvars,vars,12,8,125970%p,12),
    monomial_x(xvars,vars,13,7,77520%p,13),
    monomial_x(xvars,vars,14,6,38760%p,14),
    monomial_x(xvars,vars,15,5,15504%p,15),
    monomial_x(xvars,vars,16,4,4845%p,16),
    monomial_x(xvars,vars,17,3,1140%p,17),
    monomial_x(xvars,vars,18,2,190%p,18),
    monomial_x(xvars,vars,19,1,20%p,19),
    monomial_x(xvars,&emptyvect,20,NONE,1,20)
                                       });
                 }

                     case 21:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,21,1,0),
    monomial_x(xvars,vars,1,20,21%p,1),
    monomial_x(xvars,vars,2,19,210%p,2),
    monomial_x(xvars,vars,3,18,1330%p,3),
    monomial_x(xvars,vars,4,17,5985%p,4),
    monomial_x(xvars,vars,5,16,20349%p,5),
    monomial_x(xvars,vars,6,15,54264%p,6),
    monomial_x(xvars,vars,7,14,116280%p,7),
    monomial_x(xvars,vars,8,13,203490%p,8),
    monomial_x(xvars,vars,9,12,293930%p,9),
    monomial_x(xvars,vars,10,11,352716%p,10),
    monomial_x(xvars,vars,11,10,352716%p,11),
    monomial_x(xvars,vars,12,9,293930%p,12),
    monomial_x(xvars,vars,13,8,203490%p,13),
    monomial_x(xvars,vars,14,7,116280%p,14),
    monomial_x(xvars,vars,15,6,54264%p,15),
    monomial_x(xvars,vars,16,5,20349%p,16),
    monomial_x(xvars,vars,17,4,5985%p,17),
    monomial_x(xvars,vars,18,3,1330%p,18),
    monomial_x(xvars,vars,19,2,210%p,19),
    monomial_x(xvars,vars,20,1,21%p,20),
    monomial_x(xvars,&emptyvect,21,NONE,1,21)

                             });
                     }
                     case 22:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,22,1,0),
    monomial_x(xvars,vars,1,21,22%p,1),
    monomial_x(xvars,vars,2,20,231%p,2),
    monomial_x(xvars,vars,3,19,1540%p,3),
    monomial_x(xvars,vars,4,18,7315%p,4),
    monomial_x(xvars,vars,5,17,26334%p,5),
    monomial_x(xvars,vars,6,16,74613%p,6),
    monomial_x(xvars,vars,7,15,170544%p,7),
    monomial_x(xvars,vars,8,14,319770%p,8),
    monomial_x(xvars,vars,9,13,497420%p,9),
    monomial_x(xvars,vars,10,12,646646%p,10),
    monomial_x(xvars,vars,11,11,705432%p,11),
    monomial_x(xvars,vars,12,10,646646%p,12),
    monomial_x(xvars,vars,13,9,497420%p,13),
    monomial_x(xvars,vars,14,8,319770%p,14),
    monomial_x(xvars,vars,15,7,170544%p,15),
    monomial_x(xvars,vars,16,6,74613%p,16),
    monomial_x(xvars,vars,17,5,26334%p,17),
    monomial_x(xvars,vars,18,4,7315%p,18),
    monomial_x(xvars,vars,19,3,1540%p,19),
    monomial_x(xvars,vars,20,2,231%p,20),
    monomial_x(xvars,vars,21,1,22%p,21),
    monomial_x(xvars,&emptyvect,22,NONE,1,22)

                             });
                             }

                     case 23:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,23,1,0),
    monomial_x(xvars,vars,1,22,23%p,1),
    monomial_x(xvars,vars,2,21,253%p,2),
    monomial_x(xvars,vars,3,20,1771%p,3),
    monomial_x(xvars,vars,4,19,8855%p,4),
    monomial_x(xvars,vars,5,18,33649%p,5),
    monomial_x(xvars,vars,6,17,100947%p,6),
    monomial_x(xvars,vars,7,16,245157%p,7),
    monomial_x(xvars,vars,8,15,490314%p,8),
    monomial_x(xvars,vars,9,14,817190%p,9),
    monomial_x(xvars,vars,10,13,1144066%p,10),
    monomial_x(xvars,vars,11,12,1352078%p,11),
    monomial_x(xvars,vars,12,11,1352078%p,12),
    monomial_x(xvars,vars,13,10,1144066%p,13),
    monomial_x(xvars,vars,14,9,817190%p,14),
    monomial_x(xvars,vars,15,8,490314%p,15),
    monomial_x(xvars,vars,16,7,245157%p,16),
    monomial_x(xvars,vars,17,6,100947%p,17),
    monomial_x(xvars,vars,18,5,33649%p,18),
    monomial_x(xvars,vars,19,4,8855%p,19),
    monomial_x(xvars,vars,20,3,1771%p,20),
    monomial_x(xvars,vars,21,2,253%p,21),
    monomial_x(xvars,vars,22,1,23%p,22),
    monomial_x(xvars,&emptyvect,23,NONE,1,23)

                             });
             }

                     case 24:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,24,1,0),
    monomial_x(xvars,vars,1,23,24%p,1),
    monomial_x(xvars,vars,2,22,276%p,2),
    monomial_x(xvars,vars,3,21,2024%p,3),
    monomial_x(xvars,vars,4,20,10626%p,4),
    monomial_x(xvars,vars,5,19,42504%p,5),
    monomial_x(xvars,vars,6,18,134596%p,6),
    monomial_x(xvars,vars,7,17,346104%p,7),
    monomial_x(xvars,vars,8,16,735471%p,8),
    monomial_x(xvars,vars,9,15,1307504%p,9),
    monomial_x(xvars,vars,10,14,1961256%p,10),
    monomial_x(xvars,vars,11,13,2496144%p,11),
    monomial_x(xvars,vars,12,12,2704156%p,12),
    monomial_x(xvars,vars,13,11,2496144%p,13),
    monomial_x(xvars,vars,14,10,1961256%p,14),
    monomial_x(xvars,vars,15,9,1307504%p,15),
    monomial_x(xvars,vars,16,8,735471%p,16),
    monomial_x(xvars,vars,17,7,346104%p,17),
    monomial_x(xvars,vars,18,6,134596%p,18),
    monomial_x(xvars,vars,19,5,42504%p,19),
    monomial_x(xvars,vars,20,4,10626%p,20),
    monomial_x(xvars,vars,21,3,2024%p,21),
    monomial_x(xvars,vars,22,2,276%p,22),
    monomial_x(xvars,vars,23,1,24%p,23),
    monomial_x(xvars,&emptyvect,24,NONE,1,24)

                             });
             }

                     case 25:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,25,1,0),
    monomial_x(xvars,vars,1,24,25%p,1),
    monomial_x(xvars,vars,2,23,300%p,2),
    monomial_x(xvars,vars,3,22,2300%p,3),
    monomial_x(xvars,vars,4,21,12650%p,4),
    monomial_x(xvars,vars,5,20,53130%p,5),
    monomial_x(xvars,vars,6,19,177100%p,6),
    monomial_x(xvars,vars,7,18,480700%p,7),
    monomial_x(xvars,vars,8,17,1081575%p,8),
    monomial_x(xvars,vars,9,16,2042975%p,9),
    monomial_x(xvars,vars,10,15,3268760%p,10),
    monomial_x(xvars,vars,11,14,4457400%p,11),
    monomial_x(xvars,vars,12,13,5200300%p,12),
    monomial_x(xvars,vars,13,12,5200300%p,13),
    monomial_x(xvars,vars,14,11,4457400%p,14),
    monomial_x(xvars,vars,15,10,3268760%p,15),
    monomial_x(xvars,vars,16,9,2042975%p,16),
    monomial_x(xvars,vars,17,8,1081575%p,17),
    monomial_x(xvars,vars,18,7,480700%p,18),
    monomial_x(xvars,vars,19,6,177100%p,19),
    monomial_x(xvars,vars,20,5,53130%p,20),
    monomial_x(xvars,vars,21,4,12650%p,21),
    monomial_x(xvars,vars,22,3,2300%p,22),
    monomial_x(xvars,vars,23,2,300%p,23),
    monomial_x(xvars,vars,24,1,25%p,24),
    monomial_x(xvars,&emptyvect,25,NONE,1,25)

                             });
             }

                     case 26:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,26,1,0),
    monomial_x(xvars,vars,1,25,26%p,1),
    monomial_x(xvars,vars,2,24,325%p,2),
    monomial_x(xvars,vars,3,23,2600%p,3),
    monomial_x(xvars,vars,4,22,14950%p,4),
    monomial_x(xvars,vars,5,21,65780%p,5),
    monomial_x(xvars,vars,6,20,230230%p,6),
    monomial_x(xvars,vars,7,19,657800%p,7),
    monomial_x(xvars,vars,8,18,1562275%p,8),
    monomial_x(xvars,vars,9,17,3124550%p,9),
    monomial_x(xvars,vars,10,16,5311735%p,10),
    monomial_x(xvars,vars,11,15,7726160%p,11),
    monomial_x(xvars,vars,12,14,9657700%p,12),
    monomial_x(xvars,vars,13,13,10400600%p,13),
    monomial_x(xvars,vars,14,12,9657700%p,14),
    monomial_x(xvars,vars,15,11,7726160%p,15),
    monomial_x(xvars,vars,16,10,5311735%p,16),
    monomial_x(xvars,vars,17,9,3124550%p,17),
    monomial_x(xvars,vars,18,8,1562275%p,18),
    monomial_x(xvars,vars,19,7,657800%p,19),
    monomial_x(xvars,vars,20,6,230230%p,20),
    monomial_x(xvars,vars,21,5,65780%p,21),
    monomial_x(xvars,vars,22,4,14950%p,22),
    monomial_x(xvars,vars,23,3,2600%p,23),
    monomial_x(xvars,vars,24,2,325%p,24),
    monomial_x(xvars,vars,25,1,26%p,25),
    monomial_x(xvars,&emptyvect,26,NONE,1,26)

                             });
             }

                     case 27:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,27,1,0),
    monomial_x(xvars,vars,1,26,27%p,1),
    monomial_x(xvars,vars,2,25,351%p,2),
    monomial_x(xvars,vars,3,24,2925%p,3),
    monomial_x(xvars,vars,4,23,17550%p,4),
    monomial_x(xvars,vars,5,22,80730%p,5),
    monomial_x(xvars,vars,6,21,296010%p,6),
    monomial_x(xvars,vars,7,20,888030%p,7),
    monomial_x(xvars,vars,8,19,2220075%p,8),
    monomial_x(xvars,vars,9,18,4686825%p,9),
    monomial_x(xvars,vars,10,17,8436285%p,10),
    monomial_x(xvars,vars,11,16,13037895%p,11),
    monomial_x(xvars,vars,12,15,17383860%p,12),
    monomial_x(xvars,vars,13,14,20058300%p,13),
    monomial_x(xvars,vars,14,13,20058300%p,14),
    monomial_x(xvars,vars,15,12,17383860%p,15),
    monomial_x(xvars,vars,16,11,13037895%p,16),
    monomial_x(xvars,vars,17,10,8436285%p,17),
    monomial_x(xvars,vars,18,9,4686825%p,18),
    monomial_x(xvars,vars,19,8,2220075%p,19),
    monomial_x(xvars,vars,20,7,888030%p,20),
    monomial_x(xvars,vars,21,6,296010%p,21),
    monomial_x(xvars,vars,22,5,80730%p,22),
    monomial_x(xvars,vars,23,4,17550%p,23),
    monomial_x(xvars,vars,24,3,2925%p,24),
    monomial_x(xvars,vars,25,2,351%p,25),
    monomial_x(xvars,vars,26,1,27%p,26),
    monomial_x(xvars,&emptyvect,27,NONE,1,27)

                             });
             }
                     case 28:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,28,1,0),
    monomial_x(xvars,vars,1,27,28%p,1),
    monomial_x(xvars,vars,2,26,378%p,2),
    monomial_x(xvars,vars,3,25,3276%p,3),
    monomial_x(xvars,vars,4,24,20475%p,4),
    monomial_x(xvars,vars,5,23,98280%p,5),
    monomial_x(xvars,vars,6,22,376740%p,6),
    monomial_x(xvars,vars,7,21,1184040%p,7),
    monomial_x(xvars,vars,8,20,3108105%p,8),
    monomial_x(xvars,vars,9,19,6906900%p,9),
    monomial_x(xvars,vars,10,18,13123110%p,10),
    monomial_x(xvars,vars,11,17,21474180%p,11),
    monomial_x(xvars,vars,12,16,30421755%p,12),
    monomial_x(xvars,vars,13,15,37442160%p,13),
    monomial_x(xvars,vars,14,14,40116600%p,14),
    monomial_x(xvars,vars,15,13,37442160%p,15),
    monomial_x(xvars,vars,16,12,30421755%p,16),
    monomial_x(xvars,vars,17,11,21474180%p,17),
    monomial_x(xvars,vars,18,10,13123110%p,18),
    monomial_x(xvars,vars,19,9,6906900%p,19),
    monomial_x(xvars,vars,20,8,3108105%p,20),
    monomial_x(xvars,vars,21,7,1184040%p,21),
    monomial_x(xvars,vars,22,6,376740%p,22),
    monomial_x(xvars,vars,23,5,98280%p,23),
    monomial_x(xvars,vars,24,4,20475%p,24),
    monomial_x(xvars,vars,25,3,3276%p,25),
    monomial_x(xvars,vars,26,2,378%p,26),
    monomial_x(xvars,vars,27,1,28%p,27),
    monomial_x(xvars,&emptyvect,28,NONE,1,28),

                             });
             }

                     case 29:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,29,1,0),
    monomial_x(xvars,vars,1,28,29%p,1),
    monomial_x(xvars,vars,2,27,406%p,2),
    monomial_x(xvars,vars,3,26,3654%p,3),
    monomial_x(xvars,vars,4,25,23751%p,4),
    monomial_x(xvars,vars,5,24,118755%p,5),
    monomial_x(xvars,vars,6,23,475020%p,6),
    monomial_x(xvars,vars,7,22,1560780%p,7),
    monomial_x(xvars,vars,8,21,4292145%p,8),
    monomial_x(xvars,vars,9,20,10015005%p,9),
    monomial_x(xvars,vars,10,19,20030010%p,10),
    monomial_x(xvars,vars,11,18,34597290%p,11),
    monomial_x(xvars,vars,12,17,51895935%p,12),
    monomial_x(xvars,vars,13,16,67863915%p,13),
    monomial_x(xvars,vars,14,15,77558760%p,14),
    monomial_x(xvars,vars,15,14,77558760%p,15),
    monomial_x(xvars,vars,16,13,67863915%p,16),
    monomial_x(xvars,vars,17,12,51895935%p,17),
    monomial_x(xvars,vars,18,11,34597290%p,18),
    monomial_x(xvars,vars,19,10,20030010%p,19),
    monomial_x(xvars,vars,20,9,10015005%p,20),
    monomial_x(xvars,vars,21,8,4292145%p,21),
    monomial_x(xvars,vars,22,7,1560780%p,22),
    monomial_x(xvars,vars,23,6,475020%p,23),
    monomial_x(xvars,vars,24,5,118755%p,24),
    monomial_x(xvars,vars,25,4,23751%p,25),
    monomial_x(xvars,vars,26,3,3654%p,26),
    monomial_x(xvars,vars,27,2,406%p,27),
    monomial_x(xvars,vars,28,1,29%p,28),
    monomial_x(xvars,&emptyvect,29,NONE,1,29),

                             });
             }
                     case 30:{
                    return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,30,1,0),
    monomial_x(xvars,vars,1,29,30%p,1),
    monomial_x(xvars,vars,2,28,435%p,2),
    monomial_x(xvars,vars,3,27,4060%p,3),
    monomial_x(xvars,vars,4,26,27405%p,4),
    monomial_x(xvars,vars,5,25,142506%p,5),
    monomial_x(xvars,vars,6,24,593775%p,6),
    monomial_x(xvars,vars,7,23,2035800%p,7),
    monomial_x(xvars,vars,8,22,5852925%p,8),
    monomial_x(xvars,vars,9,21,14307150%p,9),
    monomial_x(xvars,vars,10,20,30045015%p,10),
    monomial_x(xvars,vars,11,19,54627300%p,11),
    monomial_x(xvars,vars,12,18,86493225%p,12),
    monomial_x(xvars,vars,13,17,119759850%p,13),
    monomial_x(xvars,vars,14,16,145422675%p,14),
    monomial_x(xvars,vars,15,15,155117520%p,15),
    monomial_x(xvars,vars,16,14,145422675%p,16),
    monomial_x(xvars,vars,17,13,119759850%p,17),
    monomial_x(xvars,vars,18,12,86493225%p,18),
    monomial_x(xvars,vars,19,11,54627300%p,19),
    monomial_x(xvars,vars,20,10,30045015%p,20),
    monomial_x(xvars,vars,21,9,14307150%p,21),
    monomial_x(xvars,vars,22,8,5852925%p,22),
    monomial_x(xvars,vars,23,7,2035800%p,23),
    monomial_x(xvars,vars,24,6,593775%p,24),
    monomial_x(xvars,vars,25,5,142506%p,25),
    monomial_x(xvars,vars,26,4,27405%p,26),
    monomial_x(xvars,vars,27,3,4060%p,27),
    monomial_x(xvars,vars,28,2,435%p,28),
    monomial_x(xvars,vars,29,1,30%p,29),
    monomial_x(xvars,&emptyvect,30,NONE,1,30),

                             });
             }

      case 31: {
                return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,31,1,0),
    monomial_x(xvars,vars,1,30,31%p,1),
    monomial_x(xvars,vars,2,29,465%p,2),
    monomial_x(xvars,vars,3,28,4495%p,3),
    monomial_x(xvars,vars,4,27,31465%p,4),
    monomial_x(xvars,vars,5,26,169911%p,5),
    monomial_x(xvars,vars,6,25,736281%p,6),
    monomial_x(xvars,vars,7,24,2629575%p,7),
    monomial_x(xvars,vars,8,23,7888725%p,8),
    monomial_x(xvars,vars,9,22,20160075%p,9),
    monomial_x(xvars,vars,10,21,44352165%p,10),
    monomial_x(xvars,vars,11,20,84672315%p,11),
    monomial_x(xvars,vars,12,19,141120525%p,12),
    monomial_x(xvars,vars,13,18,206253075%p,13),
    monomial_x(xvars,vars,14,17,265182525%p,14),
    monomial_x(xvars,vars,15,16,300540195%p,15),
    monomial_x(xvars,vars,16,15,300540195%p,16),
    monomial_x(xvars,vars,17,14,265182525%p,17),
    monomial_x(xvars,vars,18,13,206253075%p,18),
    monomial_x(xvars,vars,19,12,141120525%p,19),
    monomial_x(xvars,vars,20,11,84672315%p,20),
    monomial_x(xvars,vars,21,10,44352165%p,21),
    monomial_x(xvars,vars,22,9,20160075%p,22),
    monomial_x(xvars,vars,23,8,7888725%p,23),
    monomial_x(xvars,vars,24,7,2629575%p,24),
    monomial_x(xvars,vars,25,6,736281%p,25),
    monomial_x(xvars,vars,26,5,169911%p,26),
    monomial_x(xvars,vars,27,4,31465%p,27),
    monomial_x(xvars,vars,28,3,4495%p,28),
    monomial_x(xvars,vars,29,2,465%p,29),
    monomial_x(xvars,vars,30,1,31%p,30),
    monomial_x(xvars,&emptyvect,31,NONE,1,31),

                 });
              }

      case 32: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,32,1,0),
    monomial_x(xvars,vars,1,31,32%p,1),
    monomial_x(xvars,vars,2,30,496%p,2),
    monomial_x(xvars,vars,3,29,4960%p,3),
    monomial_x(xvars,vars,4,28,35960%p,4),
    monomial_x(xvars,vars,5,27,201376%p,5),
    monomial_x(xvars,vars,6,26,906192%p,6),
    monomial_x(xvars,vars,7,25,3365856%p,7),
    monomial_x(xvars,vars,8,24,10518300%p,8),
    monomial_x(xvars,vars,9,23,28048800%p,9),
    monomial_x(xvars,vars,10,22,64512240%p,10),
    monomial_x(xvars,vars,11,21,129024480%p,11),
    monomial_x(xvars,vars,12,20,225792840%p,12),
    monomial_x(xvars,vars,13,19,347373600%p,13),
    monomial_x(xvars,vars,14,18,471435600%p,14),
    monomial_x(xvars,vars,15,17,565722720%p,15),
    monomial_x(xvars,vars,16,16,601080390%p,16),
    monomial_x(xvars,vars,17,15,565722720%p,17),
    monomial_x(xvars,vars,18,14,471435600%p,18),
    monomial_x(xvars,vars,19,13,347373600%p,19),
    monomial_x(xvars,vars,20,12,225792840%p,20),
    monomial_x(xvars,vars,21,11,129024480%p,21),
    monomial_x(xvars,vars,22,10,64512240%p,22),
    monomial_x(xvars,vars,23,9,28048800%p,23),
    monomial_x(xvars,vars,24,8,10518300%p,24),
    monomial_x(xvars,vars,25,7,3365856%p,25),
    monomial_x(xvars,vars,26,6,906192%p,26),
    monomial_x(xvars,vars,27,5,201376%p,27),
    monomial_x(xvars,vars,28,4,35960%p,28),
    monomial_x(xvars,vars,29,3,4960%p,29),
    monomial_x(xvars,vars,30,2,496%p,30),
    monomial_x(xvars,vars,31,1,32%p,31),
    monomial_x(xvars,&emptyvect,32,NONE,1,32),

                 });

              }
      case 33: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,33,1,0),
    monomial_x(xvars,vars,1,32,33%p,1),
    monomial_x(xvars,vars,2,31,528%p,2),
    monomial_x(xvars,vars,3,30,5456%p,3),
    monomial_x(xvars,vars,4,29,40920%p,4),
    monomial_x(xvars,vars,5,28,237336%p,5),
    monomial_x(xvars,vars,6,27,1107568%p,6),
    monomial_x(xvars,vars,7,26,4272048%p,7),
    monomial_x(xvars,vars,8,25,13884156%p,8),
    monomial_x(xvars,vars,9,24,38567100%p,9),
    monomial_x(xvars,vars,10,23,92561040%p,10),
    monomial_x(xvars,vars,11,22,193536720%p,11),
    monomial_x(xvars,vars,12,21,354817320%p,12),
    monomial_x(xvars,vars,13,20,573166440%p,13),
    monomial_x(xvars,vars,14,19,818809200%p,14),
    monomial_x(xvars,vars,15,18,1037158320%p,15),
    monomial_x(xvars,vars,16,17,1166803110%p,16),
    monomial_x(xvars,vars,17,16,1166803110%p,17),
    monomial_x(xvars,vars,18,15,1037158320%p,18),
    monomial_x(xvars,vars,19,14,818809200%p,19),
    monomial_x(xvars,vars,20,13,573166440%p,20),
    monomial_x(xvars,vars,21,12,354817320%p,21),
    monomial_x(xvars,vars,22,11,193536720%p,22),
    monomial_x(xvars,vars,23,10,92561040%p,23),
    monomial_x(xvars,vars,24,9,38567100%p,24),
    monomial_x(xvars,vars,25,8,13884156%p,25),
    monomial_x(xvars,vars,26,7,4272048%p,26),
    monomial_x(xvars,vars,27,6,1107568%p,27),
    monomial_x(xvars,vars,28,5,237336%p,28),
    monomial_x(xvars,vars,29,4,40920%p,29),
    monomial_x(xvars,vars,30,3,5456%p,30),
    monomial_x(xvars,vars,31,2,528%p,31),
    monomial_x(xvars,vars,32,1,33%p,32),
    monomial_x(xvars,&emptyvect,33,NONE,1,33),

                 });

              }
      case 34: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,34,1,0),
    monomial_x(xvars,vars,1,33,34%p,1),
    monomial_x(xvars,vars,2,32,561%p,2),
    monomial_x(xvars,vars,3,31,5984%p,3),
    monomial_x(xvars,vars,4,30,46376%p,4),
    monomial_x(xvars,vars,5,29,278256%p,5),
    monomial_x(xvars,vars,6,28,1344904%p,6),
    monomial_x(xvars,vars,7,27,5379616%p,7),
    monomial_x(xvars,vars,8,26,18156204%p,8),
    monomial_x(xvars,vars,9,25,52451256%p,9),
    monomial_x(xvars,vars,10,24,131128140%p,10),
    monomial_x(xvars,vars,11,23,286097760%p,11),
    monomial_x(xvars,vars,12,22,548354040%p,12),
    monomial_x(xvars,vars,13,21,927983760%p,13),
    monomial_x(xvars,vars,14,20,1391975640%p,14),
    monomial_x(xvars,vars,15,19,1855967520%p,15),
    monomial_x(xvars,vars,16,18,2203961430%p,16),
    monomial_x(xvars,vars,17,17,2333606220%p,17),
    monomial_x(xvars,vars,18,16,2203961430%p,18),
    monomial_x(xvars,vars,19,15,1855967520%p,19),
    monomial_x(xvars,vars,20,14,1391975640%p,20),
    monomial_x(xvars,vars,21,13,927983760%p,21),
    monomial_x(xvars,vars,22,12,548354040%p,22),
    monomial_x(xvars,vars,23,11,286097760%p,23),
    monomial_x(xvars,vars,24,10,131128140%p,24),
    monomial_x(xvars,vars,25,9,52451256%p,25),
    monomial_x(xvars,vars,26,8,18156204%p,26),
    monomial_x(xvars,vars,27,7,5379616%p,27),
    monomial_x(xvars,vars,28,6,1344904%p,28),
    monomial_x(xvars,vars,29,5,278256%p,29),
    monomial_x(xvars,vars,30,4,46376%p,30),
    monomial_x(xvars,vars,31,3,5984%p,31),
    monomial_x(xvars,vars,32,2,561%p,32),
    monomial_x(xvars,vars,33,1,34%p,33),
    monomial_x(xvars,&emptyvect,34,NONE,1,34),

                 });

              }
      case 35: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,35,1,0),
    monomial_x(xvars,vars,1,34,35%p,1),
    monomial_x(xvars,vars,2,33,595%p,2),
    monomial_x(xvars,vars,3,32,6545%p,3),
    monomial_x(xvars,vars,4,31,52360%p,4),
    monomial_x(xvars,vars,5,30,324632%p,5),
    monomial_x(xvars,vars,6,29,1623160%p,6),
    monomial_x(xvars,vars,7,28,6724520%p,7),
    monomial_x(xvars,vars,8,27,23535820%p,8),
    monomial_x(xvars,vars,9,26,70607460%p,9),
    monomial_x(xvars,vars,10,25,183579396%p,10),
    monomial_x(xvars,vars,11,24,417225900%p,11),
    monomial_x(xvars,vars,12,23,834451800%p,12),
    monomial_x(xvars,vars,13,22,1476337800%p,13),
    monomial_x(xvars,vars,14,21,2319959400%p,14),
    monomial_x(xvars,vars,15,20,3247943160%p,15),
    monomial_x(xvars,vars,16,19,4059928950%p,16),
    monomial_x(xvars,vars,17,18,4537567650%p,17),
    monomial_x(xvars,vars,18,17,4537567650%p,18),
    monomial_x(xvars,vars,19,16,4059928950%p,19),
    monomial_x(xvars,vars,20,15,3247943160%p,20),
    monomial_x(xvars,vars,21,14,2319959400%p,21),
    monomial_x(xvars,vars,22,13,1476337800%p,22),
    monomial_x(xvars,vars,23,12,834451800%p,23),
    monomial_x(xvars,vars,24,11,417225900%p,24),
    monomial_x(xvars,vars,25,10,183579396%p,25),
    monomial_x(xvars,vars,26,9,70607460%p,26),
    monomial_x(xvars,vars,27,8,23535820%p,27),
    monomial_x(xvars,vars,28,7,6724520%p,28),
    monomial_x(xvars,vars,29,6,1623160%p,29),
    monomial_x(xvars,vars,30,5,324632%p,30),
    monomial_x(xvars,vars,31,4,52360%p,31),
    monomial_x(xvars,vars,32,3,6545%p,32),
    monomial_x(xvars,vars,33,2,595%p,33),
    monomial_x(xvars,vars,34,1,35%p,34),
    monomial_x(xvars,&emptyvect,35,NONE,1,35),

                 });

              }
      case 36: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,36,1,0),
    monomial_x(xvars,vars,1,35,36%p,1),
    monomial_x(xvars,vars,2,34,630%p,2),
    monomial_x(xvars,vars,3,33,7140%p,3),
    monomial_x(xvars,vars,4,32,58905%p,4),
    monomial_x(xvars,vars,5,31,376992%p,5),
    monomial_x(xvars,vars,6,30,1947792%p,6),
    monomial_x(xvars,vars,7,29,8347680%p,7),
    monomial_x(xvars,vars,8,28,30260340%p,8),
    monomial_x(xvars,vars,9,27,94143280%p,9),
    monomial_x(xvars,vars,10,26,254186856%p,10),
    monomial_x(xvars,vars,11,25,600805296%p,11),
    monomial_x(xvars,vars,12,24,1251677700%p,12),
    monomial_x(xvars,vars,13,23,2310789600%p,13),
    monomial_x(xvars,vars,14,22,3796297200%p,14),
    monomial_x(xvars,vars,15,21,5567902560%p,15),
    monomial_x(xvars,vars,16,20,7307872110%p,16),
    monomial_x(xvars,vars,17,19,8597496600%p,17),
    monomial_x(xvars,vars,18,18,9075135300%p,18),
    monomial_x(xvars,vars,19,17,8597496600%p,19),
    monomial_x(xvars,vars,20,16,7307872110%p,20),
    monomial_x(xvars,vars,21,15,5567902560%p,21),
    monomial_x(xvars,vars,22,14,3796297200%p,22),
    monomial_x(xvars,vars,23,13,2310789600%p,23),
    monomial_x(xvars,vars,24,12,1251677700%p,24),
    monomial_x(xvars,vars,25,11,600805296%p,25),
    monomial_x(xvars,vars,26,10,254186856%p,26),
    monomial_x(xvars,vars,27,9,94143280%p,27),
    monomial_x(xvars,vars,28,8,30260340%p,28),
    monomial_x(xvars,vars,29,7,8347680%p,29),
    monomial_x(xvars,vars,30,6,1947792%p,30),
    monomial_x(xvars,vars,31,5,376992%p,31),
    monomial_x(xvars,vars,32,4,58905%p,32),
    monomial_x(xvars,vars,33,3,7140%p,33),
    monomial_x(xvars,vars,34,2,630%p,34),
    monomial_x(xvars,vars,35,1,36%p,35),
    monomial_x(xvars,&emptyvect,36,NONE,1,36),

                 });

              }
      case 37: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,37,1,0),
    monomial_x(xvars,vars,1,36,37%p,1),
    monomial_x(xvars,vars,2,35,666%p,2),
    monomial_x(xvars,vars,3,34,7770%p,3),
    monomial_x(xvars,vars,4,33,66045%p,4),
    monomial_x(xvars,vars,5,32,435897%p,5),
    monomial_x(xvars,vars,6,31,2324784%p,6),
    monomial_x(xvars,vars,7,30,10295472%p,7),
    monomial_x(xvars,vars,8,29,38608020%p,8),
    monomial_x(xvars,vars,9,28,124403620%p,9),
    monomial_x(xvars,vars,10,27,348330136%p,10),
    monomial_x(xvars,vars,11,26,854992152%p,11),
    monomial_x(xvars,vars,12,25,1852482996%p,12),
    monomial_x(xvars,vars,13,24,3562467300%p,13),
    monomial_x(xvars,vars,14,23,6107086800%p,14),
    monomial_x(xvars,vars,15,22,9364199760%p,15),
    monomial_x(xvars,vars,16,21,12875774670%p,16),
    monomial_x(xvars,vars,17,20,15905368710%p,17),
    monomial_x(xvars,vars,18,19,17672631900%p,18),
    monomial_x(xvars,vars,19,18,17672631900%p,19),
    monomial_x(xvars,vars,20,17,15905368710%p,20),
    monomial_x(xvars,vars,21,16,12875774670%p,21),
    monomial_x(xvars,vars,22,15,9364199760%p,22),
    monomial_x(xvars,vars,23,14,6107086800%p,23),
    monomial_x(xvars,vars,24,13,3562467300%p,24),
    monomial_x(xvars,vars,25,12,1852482996%p,25),
    monomial_x(xvars,vars,26,11,854992152%p,26),
    monomial_x(xvars,vars,27,10,348330136%p,27),
    monomial_x(xvars,vars,28,9,124403620%p,28),
    monomial_x(xvars,vars,29,8,38608020%p,29),
    monomial_x(xvars,vars,30,7,10295472%p,30),
    monomial_x(xvars,vars,31,6,2324784%p,31),
    monomial_x(xvars,vars,32,5,435897%p,32),
    monomial_x(xvars,vars,33,4,66045%p,33),
    monomial_x(xvars,vars,34,3,7770%p,34),
    monomial_x(xvars,vars,35,2,666%p,35),
    monomial_x(xvars,vars,36,1,37%p,36),
    monomial_x(xvars,&emptyvect,37,NONE,1,37),

                 });

              }
      case 38: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,38,1,0),
    monomial_x(xvars,vars,1,37,38%p,1),
    monomial_x(xvars,vars,2,36,703%p,2),
    monomial_x(xvars,vars,3,35,8436%p,3),
    monomial_x(xvars,vars,4,34,73815%p,4),
    monomial_x(xvars,vars,5,33,501942%p,5),
    monomial_x(xvars,vars,6,32,2760681%p,6),
    monomial_x(xvars,vars,7,31,12620256%p,7),
    monomial_x(xvars,vars,8,30,48903492%p,8),
    monomial_x(xvars,vars,9,29,163011640%p,9),
    monomial_x(xvars,vars,10,28,472733756%p,10),
    monomial_x(xvars,vars,11,27,1203322288%p,11),
    monomial_x(xvars,vars,12,26,2707475148%p,12),
    monomial_x(xvars,vars,13,25,5414950296%p,13),
    monomial_x(xvars,vars,14,24,9669554100%p,14),
    monomial_x(xvars,vars,15,23,15471286560%p,15),
    monomial_x(xvars,vars,16,22,22239974430%p,16),
    monomial_x(xvars,vars,17,21,28781143380%p,17),
    monomial_x(xvars,vars,18,20,33578000610%p,18),
    monomial_x(xvars,vars,19,19,35345263800%p,19),
    monomial_x(xvars,vars,20,18,33578000610%p,20),
    monomial_x(xvars,vars,21,17,28781143380%p,21),
    monomial_x(xvars,vars,22,16,22239974430%p,22),
    monomial_x(xvars,vars,23,15,15471286560%p,23),
    monomial_x(xvars,vars,24,14,9669554100%p,24),
    monomial_x(xvars,vars,25,13,5414950296%p,25),
    monomial_x(xvars,vars,26,12,2707475148%p,26),
    monomial_x(xvars,vars,27,11,1203322288%p,27),
    monomial_x(xvars,vars,28,10,472733756%p,28),
    monomial_x(xvars,vars,29,9,163011640%p,29),
    monomial_x(xvars,vars,30,8,48903492%p,30),
    monomial_x(xvars,vars,31,7,12620256%p,31),
    monomial_x(xvars,vars,32,6,2760681%p,32),
    monomial_x(xvars,vars,33,5,501942%p,33),
    monomial_x(xvars,vars,34,4,73815%p,34),
    monomial_x(xvars,vars,35,3,8436%p,35),
    monomial_x(xvars,vars,36,2,703%p,36),
    monomial_x(xvars,vars,37,1,38%p,37),
    monomial_x(xvars,&emptyvect,38,NONE,1,38),

                 });

              }
      case 39: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,39,1,0),
    monomial_x(xvars,vars,1,38,39%p,1),
    monomial_x(xvars,vars,2,37,741%p,2),
    monomial_x(xvars,vars,3,36,9139%p,3),
    monomial_x(xvars,vars,4,35,82251%p,4),
    monomial_x(xvars,vars,5,34,575757%p,5),
    monomial_x(xvars,vars,6,33,3262623%p,6),
    monomial_x(xvars,vars,7,32,15380937%p,7),
    monomial_x(xvars,vars,8,31,61523748%p,8),
    monomial_x(xvars,vars,9,30,211915132%p,9),
    monomial_x(xvars,vars,10,29,635745396%p,10),
    monomial_x(xvars,vars,11,28,1676056044%p,11),
    monomial_x(xvars,vars,12,27,3910797436%p,12),
    monomial_x(xvars,vars,13,26,8122425444%p,13),
    monomial_x(xvars,vars,14,25,15084504396%p,14),
    monomial_x(xvars,vars,15,24,25140840660%p,15),
    monomial_x(xvars,vars,16,23,37711260990%p,16),
    monomial_x(xvars,vars,17,22,51021117810%p,17),
    monomial_x(xvars,vars,18,21,62359143990%p,18),
    monomial_x(xvars,vars,19,20,68923264410%p,19),
    monomial_x(xvars,vars,20,19,68923264410%p,20),
    monomial_x(xvars,vars,21,18,62359143990%p,21),
    monomial_x(xvars,vars,22,17,51021117810%p,22),
    monomial_x(xvars,vars,23,16,37711260990%p,23),
    monomial_x(xvars,vars,24,15,25140840660%p,24),
    monomial_x(xvars,vars,25,14,15084504396%p,25),
    monomial_x(xvars,vars,26,13,8122425444%p,26),
    monomial_x(xvars,vars,27,12,3910797436%p,27),
    monomial_x(xvars,vars,28,11,1676056044%p,28),
    monomial_x(xvars,vars,29,10,635745396%p,29),
    monomial_x(xvars,vars,30,9,211915132%p,30),
    monomial_x(xvars,vars,31,8,61523748%p,31),
    monomial_x(xvars,vars,32,7,15380937%p,32),
    monomial_x(xvars,vars,33,6,3262623%p,33),
    monomial_x(xvars,vars,34,5,575757%p,34),
    monomial_x(xvars,vars,35,4,82251%p,35),
    monomial_x(xvars,vars,36,3,9139%p,36),
    monomial_x(xvars,vars,37,2,741%p,37),
    monomial_x(xvars,vars,38,1,39%p,38),
    monomial_x(xvars,&emptyvect,39,NONE,1,39),

                 });

              }

      case 40: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,40,1,0),
    monomial_x(xvars,vars,1,39,40%p,1),
    monomial_x(xvars,vars,2,38,780%p,2),
    monomial_x(xvars,vars,3,37,9880%p,3),
    monomial_x(xvars,vars,4,36,91390%p,4),
    monomial_x(xvars,vars,5,35,658008%p,5),
    monomial_x(xvars,vars,6,34,3838380%p,6),
    monomial_x(xvars,vars,7,33,18643560%p,7),
    monomial_x(xvars,vars,8,32,76904685%p,8),
    monomial_x(xvars,vars,9,31,273438880%p,9),
    monomial_x(xvars,vars,10,30,847660528%p,10),
    monomial_x(xvars,vars,11,29,2311801440%p,11),
    monomial_x(xvars,vars,12,28,5586853480%p,12),
    monomial_x(xvars,vars,13,27,12033222880%p,13),
    monomial_x(xvars,vars,14,26,23206929840%p,14),
    monomial_x(xvars,vars,15,25,40225345056%p,15),
    monomial_x(xvars,vars,16,24,62852101650%p,16),
    monomial_x(xvars,vars,17,23,88732378800%p,17),
    monomial_x(xvars,vars,18,22,113380261800%p,18),
    monomial_x(xvars,vars,19,21,131282408400%p,19),
    monomial_x(xvars,vars,20,20,137846528820%p,20),
    monomial_x(xvars,vars,21,19,131282408400%p,21),
    monomial_x(xvars,vars,22,18,113380261800%p,22),
    monomial_x(xvars,vars,23,17,88732378800%p,23),
    monomial_x(xvars,vars,24,16,62852101650%p,24),
    monomial_x(xvars,vars,25,15,40225345056%p,25),
    monomial_x(xvars,vars,26,14,23206929840%p,26),
    monomial_x(xvars,vars,27,13,12033222880%p,27),
    monomial_x(xvars,vars,28,12,5586853480%p,28),
    monomial_x(xvars,vars,29,11,2311801440%p,29),
    monomial_x(xvars,vars,30,10,847660528%p,30),
    monomial_x(xvars,vars,31,9,273438880%p,31),
    monomial_x(xvars,vars,32,8,76904685%p,32),
    monomial_x(xvars,vars,33,7,18643560%p,33),
    monomial_x(xvars,vars,34,6,3838380%p,34),
    monomial_x(xvars,vars,35,5,658008%p,35),
    monomial_x(xvars,vars,36,4,91390%p,36),
    monomial_x(xvars,vars,37,3,9880%p,37),
    monomial_x(xvars,vars,38,2,780%p,38),
    monomial_x(xvars,vars,39,1,40%p,39),
    monomial_x(xvars,&emptyvect,40,NONE,1,40),

                 });

              }

      case 41: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,41,1,0),
    monomial_x(xvars,vars,1,40,41%p,1),
    monomial_x(xvars,vars,2,39,820%p,2),
    monomial_x(xvars,vars,3,38,10660%p,3),
    monomial_x(xvars,vars,4,37,101270%p,4),
    monomial_x(xvars,vars,5,36,749398%p,5),
    monomial_x(xvars,vars,6,35,4496388%p,6),
    monomial_x(xvars,vars,7,34,22481940%p,7),
    monomial_x(xvars,vars,8,33,95548245%p,8),
    monomial_x(xvars,vars,9,32,350343565%p,9),
    monomial_x(xvars,vars,10,31,1121099408%p,10),
    monomial_x(xvars,vars,11,30,3159461968%p,11),
    monomial_x(xvars,vars,12,29,7898654920%p,12),
    monomial_x(xvars,vars,13,28,17620076360%p,13),
    monomial_x(xvars,vars,14,27,35240152720%p,14),
    monomial_x(xvars,vars,15,26,63432274896%p,15),
    monomial_x(xvars,vars,16,25,103077446706%p,16),
    monomial_x(xvars,vars,17,24,151584480450%p,17),
    monomial_x(xvars,vars,18,23,202112640600%p,18),
    monomial_x(xvars,vars,19,22,244662670200%p,19),
    monomial_x(xvars,vars,20,21,269128937220%p,20),
    monomial_x(xvars,vars,21,20,269128937220%p,21),
    monomial_x(xvars,vars,22,19,244662670200%p,22),
    monomial_x(xvars,vars,23,18,202112640600%p,23),
    monomial_x(xvars,vars,24,17,151584480450%p,24),
    monomial_x(xvars,vars,25,16,103077446706%p,25),
    monomial_x(xvars,vars,26,15,63432274896%p,26),
    monomial_x(xvars,vars,27,14,35240152720%p,27),
    monomial_x(xvars,vars,28,13,17620076360%p,28),
    monomial_x(xvars,vars,29,12,7898654920%p,29),
    monomial_x(xvars,vars,30,11,3159461968%p,30),
    monomial_x(xvars,vars,31,10,1121099408%p,31),
    monomial_x(xvars,vars,32,9,350343565%p,32),
    monomial_x(xvars,vars,33,8,95548245%p,33),
    monomial_x(xvars,vars,34,7,22481940%p,34),
    monomial_x(xvars,vars,35,6,4496388%p,35),
    monomial_x(xvars,vars,36,5,749398%p,36),
    monomial_x(xvars,vars,37,4,101270%p,37),
    monomial_x(xvars,vars,38,3,10660%p,38),
    monomial_x(xvars,vars,39,2,820%p,39),
    monomial_x(xvars,vars,40,1,41%p,40),
    monomial_x(xvars,&emptyvect,41,NONE,1,41),

                 });

              }
      case 42: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,42,1,0),
    monomial_x(xvars,vars,1,41,42%p,1),
    monomial_x(xvars,vars,2,40,861%p,2),
    monomial_x(xvars,vars,3,39,11480%p,3),
    monomial_x(xvars,vars,4,38,111930%p,4),
    monomial_x(xvars,vars,5,37,850668%p,5),
    monomial_x(xvars,vars,6,36,5245786%p,6),
    monomial_x(xvars,vars,7,35,26978328%p,7),
    monomial_x(xvars,vars,8,34,118030185%p,8),
    monomial_x(xvars,vars,9,33,445891810%p,9),
    monomial_x(xvars,vars,10,32,1471442973%p,10),
    monomial_x(xvars,vars,11,31,4280561376%p,11),
    monomial_x(xvars,vars,12,30,11058116888%p,12),
    monomial_x(xvars,vars,13,29,25518731280%p,13),
    monomial_x(xvars,vars,14,28,52860229080%p,14),
    monomial_x(xvars,vars,15,27,98672427616%p,15),
    monomial_x(xvars,vars,16,26,166509721602%p,16),
    monomial_x(xvars,vars,17,25,254661927156%p,17),
    monomial_x(xvars,vars,18,24,353697121050%p,18),
    monomial_x(xvars,vars,19,23,446775310800%p,19),
    monomial_x(xvars,vars,20,22,513791607420%p,20),
    monomial_x(xvars,vars,21,21,538257874440%p,21),
    monomial_x(xvars,vars,22,20,513791607420%p,22),
    monomial_x(xvars,vars,23,19,446775310800%p,23),
    monomial_x(xvars,vars,24,18,353697121050%p,24),
    monomial_x(xvars,vars,25,17,254661927156%p,25),
    monomial_x(xvars,vars,26,16,166509721602%p,26),
    monomial_x(xvars,vars,27,15,98672427616%p,27),
    monomial_x(xvars,vars,28,14,52860229080%p,28),
    monomial_x(xvars,vars,29,13,25518731280%p,29),
    monomial_x(xvars,vars,30,12,11058116888%p,30),
    monomial_x(xvars,vars,31,11,4280561376%p,31),
    monomial_x(xvars,vars,32,10,1471442973%p,32),
    monomial_x(xvars,vars,33,9,445891810%p,33),
    monomial_x(xvars,vars,34,8,118030185%p,34),
    monomial_x(xvars,vars,35,7,26978328%p,35),
    monomial_x(xvars,vars,36,6,5245786%p,36),
    monomial_x(xvars,vars,37,5,850668%p,37),
    monomial_x(xvars,vars,38,4,111930%p,38),
    monomial_x(xvars,vars,39,3,11480%p,39),
    monomial_x(xvars,vars,40,2,861%p,40),
    monomial_x(xvars,vars,41,1,42%p,41),
    monomial_x(xvars,&emptyvect,42,NONE,1,42),

                 });

              }
      case 43: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,43,1,0),
    monomial_x(xvars,vars,1,42,43%p,1),
    monomial_x(xvars,vars,2,41,903%p,2),
    monomial_x(xvars,vars,3,40,12341%p,3),
    monomial_x(xvars,vars,4,39,123410%p,4),
    monomial_x(xvars,vars,5,38,962598%p,5),
    monomial_x(xvars,vars,6,37,6096454%p,6),
    monomial_x(xvars,vars,7,36,32224114%p,7),
    monomial_x(xvars,vars,8,35,145008513%p,8),
    monomial_x(xvars,vars,9,34,563921995%p,9),
    monomial_x(xvars,vars,10,33,1917334783%p,10),
    monomial_x(xvars,vars,11,32,5752004349%p,11),
    monomial_x(xvars,vars,12,31,15338678264%p,12),
    monomial_x(xvars,vars,13,30,36576848168%p,13),
    monomial_x(xvars,vars,14,29,78378960360%p,14),
    monomial_x(xvars,vars,15,28,151532656696%p,15),
    monomial_x(xvars,vars,16,27,265182149218%p,16),
    monomial_x(xvars,vars,17,26,421171648758%p,17),
    monomial_x(xvars,vars,18,25,608359048206%p,18),
    monomial_x(xvars,vars,19,24,800472431850%p,19),
    monomial_x(xvars,vars,20,23,960566918220%p,20),
    monomial_x(xvars,vars,21,22,1052049481860%p,21),
    monomial_x(xvars,vars,22,21,1052049481860%p,22),
    monomial_x(xvars,vars,23,20,960566918220%p,23),
    monomial_x(xvars,vars,24,19,800472431850%p,24),
    monomial_x(xvars,vars,25,18,608359048206%p,25),
    monomial_x(xvars,vars,26,17,421171648758%p,26),
    monomial_x(xvars,vars,27,16,265182149218%p,27),
    monomial_x(xvars,vars,28,15,151532656696%p,28),
    monomial_x(xvars,vars,29,14,78378960360%p,29),
    monomial_x(xvars,vars,30,13,36576848168%p,30),
    monomial_x(xvars,vars,31,12,15338678264%p,31),
    monomial_x(xvars,vars,32,11,5752004349%p,32),
    monomial_x(xvars,vars,33,10,1917334783%p,33),
    monomial_x(xvars,vars,34,9,563921995%p,34),
    monomial_x(xvars,vars,35,8,145008513%p,35),
    monomial_x(xvars,vars,36,7,32224114%p,36),
    monomial_x(xvars,vars,37,6,6096454%p,37),
    monomial_x(xvars,vars,38,5,962598%p,38),
    monomial_x(xvars,vars,39,4,123410%p,39),
    monomial_x(xvars,vars,40,3,12341%p,40),
    monomial_x(xvars,vars,41,2,903%p,41),
    monomial_x(xvars,vars,42,1,43%p,42),
    monomial_x(xvars,&emptyvect,43,NONE,1,43),

                 });

              }
      case 44: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,44,1,0),
    monomial_x(xvars,vars,1,43,44%p,1),
    monomial_x(xvars,vars,2,42,946%p,2),
    monomial_x(xvars,vars,3,41,13244%p,3),
    monomial_x(xvars,vars,4,40,135751%p,4),
    monomial_x(xvars,vars,5,39,1086008%p,5),
    monomial_x(xvars,vars,6,38,7059052%p,6),
    monomial_x(xvars,vars,7,37,38320568%p,7),
    monomial_x(xvars,vars,8,36,177232627%p,8),
    monomial_x(xvars,vars,9,35,708930508%p,9),
    monomial_x(xvars,vars,10,34,2481256778%p,10),
    monomial_x(xvars,vars,11,33,7669339132%p,11),
    monomial_x(xvars,vars,12,32,21090682613%p,12),
    monomial_x(xvars,vars,13,31,51915526432%p,13),
    monomial_x(xvars,vars,14,30,114955808528%p,14),
    monomial_x(xvars,vars,15,29,229911617056%p,15),
    monomial_x(xvars,vars,16,28,416714805914%p,16),
    monomial_x(xvars,vars,17,27,686353797976%p,17),
    monomial_x(xvars,vars,18,26,1029530696964%p,18),
    monomial_x(xvars,vars,19,25,1408831480056%p,19),
    monomial_x(xvars,vars,20,24,1761039350070%p,20),
    monomial_x(xvars,vars,21,23,2012616400080%p,21),
    monomial_x(xvars,vars,22,22,2104098963720%p,22),
    monomial_x(xvars,vars,23,21,2012616400080%p,23),
    monomial_x(xvars,vars,24,20,1761039350070%p,24),
    monomial_x(xvars,vars,25,19,1408831480056%p,25),
    monomial_x(xvars,vars,26,18,1029530696964%p,26),
    monomial_x(xvars,vars,27,17,686353797976%p,27),
    monomial_x(xvars,vars,28,16,416714805914%p,28),
    monomial_x(xvars,vars,29,15,229911617056%p,29),
    monomial_x(xvars,vars,30,14,114955808528%p,30),
    monomial_x(xvars,vars,31,13,51915526432%p,31),
    monomial_x(xvars,vars,32,12,21090682613%p,32),
    monomial_x(xvars,vars,33,11,7669339132%p,33),
    monomial_x(xvars,vars,34,10,2481256778%p,34),
    monomial_x(xvars,vars,35,9,708930508%p,35),
    monomial_x(xvars,vars,36,8,177232627%p,36),
    monomial_x(xvars,vars,37,7,38320568%p,37),
    monomial_x(xvars,vars,38,6,7059052%p,38),
    monomial_x(xvars,vars,39,5,1086008%p,39),
    monomial_x(xvars,vars,40,4,135751%p,40),
    monomial_x(xvars,vars,41,3,13244%p,41),
    monomial_x(xvars,vars,42,2,946%p,42),
    monomial_x(xvars,vars,43,1,44%p,43),
    monomial_x(xvars,&emptyvect,44,NONE,1,44),

                 });

              }
      case 45: {
            return std::vector<monomial_x>({ 
monomial_x(&emptyvect,vars,NONE,45,1,0),
    monomial_x(xvars,vars,1,44,45%p,1),
    monomial_x(xvars,vars,2,43,990%p,2),
    monomial_x(xvars,vars,3,42,14190%p,3),
    monomial_x(xvars,vars,4,41,148995%p,4),
    monomial_x(xvars,vars,5,40,1221759%p,5),
    monomial_x(xvars,vars,6,39,8145060%p,6),
    monomial_x(xvars,vars,7,38,45379620%p,7),
    monomial_x(xvars,vars,8,37,215553195%p,8),
    monomial_x(xvars,vars,9,36,886163135%p,9),
    monomial_x(xvars,vars,10,35,3190187286%p,10),
    monomial_x(xvars,vars,11,34,10150595910%p,11),
    monomial_x(xvars,vars,12,33,28760021745%p,12),
    monomial_x(xvars,vars,13,32,73006209045%p,13),
    monomial_x(xvars,vars,14,31,166871334960%p,14),
    monomial_x(xvars,vars,15,30,344867425584%p,15),
    monomial_x(xvars,vars,16,29,646626422970%p,16),
    monomial_x(xvars,vars,17,28,1103068603890%p,17),
    monomial_x(xvars,vars,18,27,1715884494940%p,18),
    monomial_x(xvars,vars,19,26,2438362177020%p,19),
    monomial_x(xvars,vars,20,25,3169870830126%p,20),
    monomial_x(xvars,vars,21,24,3773655750150%p,21),
    monomial_x(xvars,vars,22,23,4116715363800%p,22),
    monomial_x(xvars,vars,23,22,4116715363800%p,23),
    monomial_x(xvars,vars,24,21,3773655750150%p,24),
    monomial_x(xvars,vars,25,20,3169870830126%p,25),
    monomial_x(xvars,vars,26,19,2438362177020%p,26),
    monomial_x(xvars,vars,27,18,1715884494940%p,27),
    monomial_x(xvars,vars,28,17,1103068603890%p,28),
    monomial_x(xvars,vars,29,16,646626422970%p,29),
    monomial_x(xvars,vars,30,15,344867425584%p,30),
    monomial_x(xvars,vars,31,14,166871334960%p,31),
    monomial_x(xvars,vars,32,13,73006209045%p,32),
    monomial_x(xvars,vars,33,12,28760021745%p,33),
    monomial_x(xvars,vars,34,11,10150595910%p,34),
    monomial_x(xvars,vars,35,10,3190187286%p,35),
    monomial_x(xvars,vars,36,9,886163135%p,36),
    monomial_x(xvars,vars,37,8,215553195%p,37),
    monomial_x(xvars,vars,38,7,45379620%p,38),
    monomial_x(xvars,vars,39,6,8145060%p,39),
    monomial_x(xvars,vars,40,5,1221759%p,40),
    monomial_x(xvars,vars,41,4,148995%p,41),
    monomial_x(xvars,vars,42,3,14190%p,42),
    monomial_x(xvars,vars,43,2,990%p,43),
    monomial_x(xvars,vars,44,1,45%p,44),
    monomial_x(xvars,&emptyvect,45,NONE,1,45),
                 });

              }

        default:{
                    //TODO
                    std::cout << int(exponent) << " shouldn't reach here, exponent\n ";
                    exit(0);
                }

    }
};

//For each monomial u_1^x u_2^y u_3^z..., we set u_1 |-> (y_1y_2..x + y_n...)^k etc
//We set up a DAG for which a directed path indicates the multiplication of monomials
//which have power of x equal to p-1
bool
obtain_multiplicands ( 
        mono_x_node* parent, 
        int current_weight,
        std::vector<std::vector<monomial_x>>& to_mult,
        unsigned int iteration){

    
    if(iteration == to_mult.size()){
        return true;
    }
    
    int max_weight_add = 0;

    for(unsigned int k = iteration + 1,end = to_mult.size(); k < end; k++){
        if(to_mult[k].size() != 1){
            max_weight_add += to_mult[k].back().exponent; 
//            max_weight_add += to_mult[k].size() - 1; 
        }

        else{
            max_weight_add += to_mult[k][0].exponent;
        }
    }

    bool badvar = true;

    for(unsigned int i = 0,end = to_mult[iteration].size(); i < end; i++){

        if(to_mult[iteration][i].cf == 0){
            continue;
        }

        else if(to_mult[iteration][i].exponent + current_weight + max_weight_add < p-1){
            continue;
        }

        else if (to_mult[iteration][i].exponent + current_weight > p-1){
            continue;
        }

        mono_x_node* possible_child = new mono_x_node(&(to_mult[iteration][i]));
//		std::cout << *possible_child->mon_ptr << '\n';

        if(obtain_multiplicands(possible_child, current_weight + to_mult[iteration][i].exponent, to_mult, iteration + 1)){
//			std::cerr << "success" << *possible_child->mon_ptr << '\n';
            parent->children.push_back(possible_child);
            badvar = false;
        }

		else{
			delete possible_child;
		}
    }

	return !badvar;

};

//Given a DAG which specifies how one should multiply monomials to get a monomial
//with power of x = p-1, we multiply on this DAG (incorrectly called a tree)
void multiply_on_tree(polynomial& toadd, const mono_x_node& node, int cf, monomial& mono_build){

//    monomial new_monomial(mono_build);
	
	int exponent = node.mon_ptr->exponent;
	int exp = node.mon_ptr->exp;

    for(auto mono = node.mon_ptr->xvars->begin(),end = node.mon_ptr->xvars->end(); mono != end; ++mono){
        int s = *mono;
       if(s >= 0){
         mono_build.vars[s] += exponent; 
       }

    }

   for(auto mono = node.mon_ptr->vars->begin(), end = node.mon_ptr->vars->end(); mono != end; ++mono){
        int s = *mono;
       if(s >= 0){
          mono_build.vars[s] += exp;; 
       }
   }

   cf = cf * node.mon_ptr->cf;
   cf %= p;
    
    if(node.children.empty()){
        {
            auto monval = toadd.find(mono_build); 
            if(monval != toadd.end()){
                monval->second += cf;
                monval->second %= p;
            }
            else{
                cf %= p;
                toadd.insert(std::make_pair(mono_build,cf));
            }
        }
    }
    else{
        for(auto it = node.children.begin(), end = node.children.end(); it!=end; ++it){
            multiply_on_tree(toadd, **it, cf, mono_build); 
        }
    }

	for(auto mono = node.mon_ptr->xvars->begin(),end = node.mon_ptr->xvars->end(); mono != end; ++mono){
        int s = *mono;
       if(s >= 0){
         mono_build.vars[s] -= exponent; 
       }

    }

   for(auto mono = node.mon_ptr->vars->begin(), end = node.mon_ptr->vars->end(); mono != end; ++mono){
        int s = *mono;
       if(s >= 0){
          mono_build.vars[s] -= exp;; 
       }
   }
}

int main (int argc, char** argv){

    omp_set_num_threads(NUM_THREADS);

    //Read the recipe file for substitution rules.
    if(argc == 1){
        std::cerr << "needs recipe\n";
        exit(1);
    }

    std::string recipe_name = std::string(argv[1]);

    std::ofstream c2_outfile("c2.txt", std::ofstream::out | std::ofstream::app);
    c2_outfile << '\n' << recipe_name << '\n' << "c2seq = ";
    c2_outfile.close();

    process_recipe(sub_maps,size_map,recipe_name);

    std::set<unsigned short> primes = {2,3,5,7,11,13,17,19,23,29,31};
    for(auto it = primes.begin(); it!= primes.end(); ++it){
        p = *it;
        vect_mono start;

        for(int i = 0; i < size_map[0]; i++){
            start.vars.push_back(std::make_pair(i,p-1));
        }

        iter_polyn actual_poly = {std::make_pair(start,1)};
        double accum = 0;
        for(unsigned int iter = 0; iter < size_map.size(); iter++){
            polynomial toadd[NUM_THREADS];

            std::cout << "size " << actual_poly.size() << '\n';
            double begin = omp_get_wtime();
           
            #pragma omp parallel for 
            for(long long k = 0; k < actual_poly.size(); k++){
                auto* mono_it = &actual_poly[k];

                if(mono_it->second != 0){
                    if(k%1000000 == 0 && k != 0){
                        std::cout << k << '\n';
                    }

                    std::vector<std::vector<monomial_x>> to_mult;
                    to_mult.reserve(20);

                    for(auto elt = mono_it->first.vars.begin(), 
                            end = mono_it->first.vars.end(); 
                            elt !=  end; 
                            ++elt){
                        to_mult.push_back(tabled_lookup(elt->first,elt->second,iter));
                    }
					
                    std::sort (to_mult.begin(), to_mult.end(), sort_function);
					mono_x_node something;
                    mono_x_node* parent = &something;
                    obtain_multiplicands(parent,0,to_mult,0);

                    for(auto it = parent->children.begin(), end = parent->children.end(); it!= end; ++it){
                        auto ptr_node = *it;
                        monomial toins;
                        if(iter+1 == size_map.size()){
                            toins.vars = std::vector<unsigned char>(1,0);
                        }
                        else{
                            toins.vars = std::vector<unsigned char>(size_map[iter+1],0);
                        }

						int index = omp_get_thread_num();
                        multiply_on_tree(toadd[index], *ptr_node, mono_it->second, toins);
                        
                    }
                }  
            }

			polynomial temp;
            actual_poly.clear();

            //We create a bunch of intermediate polynomials for parallel processing
            //this is the map reduce principle. Then we make one big polynomial.
            //Then we change the format of the big polynomial into a vector format so openmp
            //can iterate over it. This isn't memory efficient.
            
			for(int i = 0; i < NUM_THREADS; i++){
				for(auto monomial = toadd[i].begin(),end = toadd[i].end(); monomial != end; ++monomial){
					if(monomial->second %p != 0){
						auto s = temp.find(monomial->first);
						if(s != temp.end()){
							s->second += monomial->second;
							s->second %= p;
						}
						else{
							temp[monomial->first] += monomial->second %p;
						}
					}
				}
				toadd[i].clear();
			}

            actual_poly.reserve(temp.size());
            for(auto monomial = temp.begin(), end = temp.end(); monomial != end; ++monomial){
                if(monomial -> second != 0){
                    actual_poly.emplace_back(monomial->first,monomial->second);
                }
            }

            double end = omp_get_wtime();
            accum += end-begin;
    //        std::cout << i << '\n';
        }


        std::cout << "time taken " << accum << '\n';
        std::cout << actual_poly.size() << " final size\n";
        if(actual_poly.size() > 0){
            std::cout << "For p = " << int(p) << " c2 is " << actual_poly[0].second % p << '\n';
        }

        std::ofstream c2_outfile("c2.txt", std::ofstream::out | std::ofstream::app);
        if(actual_poly.size() == 0){
//            c2_outfile << "prime " << (int)p <<  ", " << 0 << '\n';
            c2_outfile << 0 << ",";;
        }
        else{
            int c2;
            if(actual_poly[0].second < 0){
                c2 = actual_poly[0].second += p;
            }
            else{
                c2 = actual_poly[0].second;
            }
//            c2_outfile << "prime " << (int)p <<  "," << c2 << '\n';
                c2_outfile << c2 << ",";
        }
        c2_outfile.close();
	}
}

